### ISSUE TITLE
jwt-bearer範例錯誤

### ISSUE THREAD

**Issue by y12studio** [od2016/OpenAPI-Specification#1]
```
{
  "type": "scheme",
  "scheme": "bearer",
  "bearerFormat": "JWT",
}
```
type應該是http

*  https://github.com/od2016/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.zhTW.md#jwt-bearer範例
* https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#jwt-bearer-sample

**Comment by typingmonk** [comment]
我目前看該錯誤已經被修正成 "type" : "http" 了，可以 close 了。
